SELECT * FROM STUDENT;

SELECT SUBSTR(name,2) FROM STUDENT;
SELECT SUBSTR(name,1,1) FROM STUDENT;
SELECT SUBSTR(name,1,1) 성씨, SUBSTR(name,2) 이름 FROM STUDENT;
-- 데이터베이스의 날짜 타입은 문자열 변환이 잘됨 (문자열 취급을 해도 됨)
SELECT ENTRANCE_DATE FROM STUDENT;
SELECT TO_CHAR(ENTRANCE_DATE) FROM STUDENT;
SELECT TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') FROM STUDENT;
SELECT TO_CHAR(ENTRANCE_DATE,'YYYY') FROM STUDENT;
SELECT SUBSTR(ENTRANCE_DATE,1,2) FROM STUDENT;
SELECT SUBSTR(TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD'),1,4) FROM STUDENT;

SELECT SUBJECT FROM EXAM_SCORE;
SELECT LOWER(SUBJECT) FROM EXAM_SCORE;
SELECT INITCAP(SUBJECT) FROM EXAM_SCORE;

SELECT * FROM EXAM_SCORE WHERE LOWER(SUBJECT)='java';

SELECT LPAD(SUBJECT,8) FROM EXAM_SCORE;
SELECT LPAD(SUBJECT,8,'#') FROM EXAM_SCORE;
SELECT RPAD(SUBJECT,8,'#') FROM EXAM_SCORE;

SELECT avg(SCORE) FROM EXAM_SCORE;
SELECT ROUND(avg(SCORE)) FROM EXAM_SCORE;
SELECT ROUND(avg(SCORE),2) FROM EXAM_SCORE;
SELECT TRUNC(avg(SCORE),2) FROM EXAM_SCORE;

SELECT SCORE/10 FROM  EXAM_SCORE;
SELECT MOD(SCORE,10) FROM  EXAM_SCORE;
-- SELECT SCORE%10 FROM  EXAM_SCORE;

-- dual 가상테이블
SELECT 1+1 FROM dual;
SELECT SYSDATE FROM dual;
SELECT TRUNC(2.1),FLOOR(2.1) FROM dual;
-- 2
SELECT TRUNC(-1.1),FLOOR(-1.1) FROM dual;
-- -1 ,-2

SELECT * FROM STUDENT;
SELECT TO_CHAR(SYSDATE,'YEAR') FROM dual;
SELECT TO_CHAR(SYSDATE,'YY-MONTH-DAY HH24:MI:SS') FROM dual;

DELETE FROM STUDENT WHERE STUDENT_ID=2023006;
-- 리터럴이 형식 문자열과 일치하지 않음 -> 문자열을 데이트 타입으로 변경
INSERT INTO student (student_id, name, dept_id, grade, entrance_date)
VALUES (2023006, '경민코딩', 'D03', 1,
        TO_DATE('24년03월04일','YY"년"MM"월"DD"일"'));
commit;
SELECT * FROM STUDENT;

-- SELECT TO_DATE('24년03월04일') FROM dual;
SELECT TO_DATE('24년03월04일','YY"년"MM"월"DD"일"') FROM dual;

SELECT * FROM EXAM_SCORE;
-- 평균이 735/10 =73.5 => 81.6 (null 을 빼고 연산)
SELECT COUNT(*) ,SUM (SCORE), AVG(SCORE) FROM EXAM_SCORE;
-- NVL  null 값 처리
SELECT AVG(NVL(SCORE,0)) FROM EXAM_SCORE;

SELECT STUDENT_ID,AVG(NVL(SCORE,0)) FROM EXAM_SCORE group by STUDENT_ID;
