SELECT * FROM STUDENT;
SELECT * FROM DEPARTMENT;
SELECT * FROM EXAM_SCORE;
commit;
UPDATE EXAM_SCORE SET  SCORE=99 WHERE STUDENT_ID=2026001 AND LOWER(SUBJECT)='database';
ROLLBACK;

INSERT INTO EXAM_SCORE (STUDENT_ID, SUBJECT, SCORE, EXAM_DATE)
VALUES (2026001,'PYTHON',99,'2023-05-01');
COMMIT;
SELECT * FROM EXAM_SCORE WHERE STUDENT_ID=2026001;

INSERT INTO STUDENT
VALUES (2022001,'월드컵',3,'2022-03-01',null);
COMMIT;
SELECT * FROM STUDENT ORDER BY STUDENT_ID ASC;

DELETE FROM EXAM_SCORE WHERE STUDENT_ID=2026001 AND SUBJECT='PYTHON';

-- SUM AVG MIN MAX COUNT DISTINCT
-- GROUP BY (그룹핑을 하면서 집계), HAVING(그룹핑한 조건으로 조회)

SELECT SUM(SCORE) FROM EXAM_SCORE;

SELECT SUBJECT,SUM(SCORE),AVG(SCORE) FROM EXAM_SCORE GROUP BY SUBJECT;
SELECT NVL(SCORE,0) FROM EXAM_SCORE ORDER BY NVL(SCORE,0);
SELECT SUBJECT,SUM(NVL(SCORE,0)),AVG(NVL(SCORE,0)) FROM EXAM_SCORE GROUP BY SUBJECT;

-- 문자열 검색 (Like % _)
SELECT * FROM STUDENT WHERE NAME LIKE '최%';
SELECT * FROM STUDENT WHERE NAME LIKE '%수%';
SELECT * FROM STUDENT WHERE NAME LIKE '____';

-- 여러조건으로 검색하기 OR IN
SELECT * FROM STUDENT WHERE DEPT_ID='D01' OR DEPT_ID='D02' ORDER BY DEPT_ID,STUDENT_ID;
SELECT * FROM STUDENT WHERE DEPT_ID in ('D01','D03') ORDER BY DEPT_ID,STUDENT_ID;
-- 범위 조회 AND BETWEEN
-- date = 년 월 일 을 분리해서 수로 저장 (문자와 수의 형변환에 친화적) (생일,이벤트)
-- timestamp = 19700101 부터 밀리초로 시가을 누적해서 저장 (게시일,저장시간..)
SELECT * FROM STUDENT WHERE ENTRANCE_DATE>='2024-01-01' AND ENTRANCE_DATE<'2026-01-01';
SELECT * FROM STUDENT WHERE ENTRANCE_DATE BETWEEN '20240101' AND '20251231';
SELECT * FROM STUDENT WHERE ENTRANCE_DATE BETWEEN '24/01/01' AND '25/12/13';
SELECT * FROM STUDENT WHERE ENTRANCE_DATE BETWEEN '24년01월01일' AND '25년12월31일';
-- 문장열 -> 변환 ( 파싱 : 어려운형변환 ) "ㅁㅁ13" -> 13
-- TO_DATE TO_CHAR
SELECT 1+1 FROM dual;
SELECT TO_DATE('2024년01월01일') FROM dual;
SELECT TO_DATE('2024년01월01일','yyyy"년"mm"월"dd"일"')+1 FROM dual;
SELECT TO_DATE('2024년01월01일 11시31분12초','yyyy"년"mm"월"dd"일" HH24"시"MI"분"SS"초"')+1 FROM dual;

SELECT * FROM STUDENT WHERE ENTRANCE_DATE
    BETWEEN TO_DATE('24년01월01일','YY"년"MM"월"DD"일"')
    AND TO_DATE('25년12월31일','YY"년"MM"월"DD"일"') ;

SELECT LPAD(NAME,8), SUBSTR(NAME,1,1) 성씨 FROM STUDENT;

SELECT LPAD(SUBJECT,8,'$') FROM EXAM_SCORE;
-- 크로스조인 : 모든 경우의 수를 가진 결합
SELECT * FROM EXAM_SCORE e,STUDENT s ORDER BY e.STUDENT_ID,e.SUBJECT;
-- 내부조인innerJoin : 조건에 맞는 데이터만
SELECT * FROM EXAM_SCORE e,STUDENT s WHERE e.STUDENT_ID=s.STUDENT_ID;

SELECT e.*,s.NAME,s.GRADE
    FROM EXAM_SCORE e,STUDENT s
    WHERE e.STUDENT_ID=s.STUDENT_ID;

SELECT * FROM DEPARTMENT;
SELECT *
    FROM STUDENT,DEPARTMENT
    ORDER BY STUDENT.STUDENT_ID;

SELECT *
FROM STUDENT,DEPARTMENT
WHERE STUDENT.DEPT_ID=DEPARTMENT.DEPT_ID
ORDER BY STUDENT.STUDENT_ID;

SELECT s.*,d.DEPT_NAME
    FROM STUDENT s, DEPARTMENT d
    WHERE s.DEPT_ID=d.DEPT_ID
    ORDER BY s.DEPT_ID;
-- INNER JOIN ON : 명시적으로 조인하는 방법
SELECT *
    FROM STUDENT s INNER JOIN DEPARTMENT d
    ON s.DEPT_ID=d.DEPT_ID;
-- NATURAL JOIN  : pk와 fk 이름이 같을때 ON 을 생략, 출력시 같은 필드는 생략
SELECT * FROM STUDENT NATURAL JOIN DEPARTMENT;
SELECT * FROM EXAM_SCORE;
-- EXAM_SCORE과 STUDENT 를 조인하세요(INNER JOIN, NATURAL JOIN)
-- EXAM_SCORE,STUDENT,DEPARTMENT 3개의 테이블을 조인하세요!

SELECT e.*,s.NAME
    FROM EXAM_SCORE e INNER JOIN STUDENT s
    ON e.STUDENT_ID=s.STUDENT_ID;

SELECT e.SUBJECT,e.SCORE,STUDENT_ID, s.NAME
    FROM EXAM_SCORE e NATURAL JOIN STUDENT s;
SELECT e.SUBJECT,e.SCORE,STUDENT_ID, s.NAME,d.DEPT_NAME
    FROM EXAM_SCORE e
        NATURAL JOIN STUDENT s
        NATURAL JOIN DEPARTMENT d;

SELECT e.*, s.NAME, s.DEPT_ID, d.DEPT_NAME
    FROM EXAM_SCORE e
    INNER JOIN STUDENT s ON e.STUDENT_ID=s.STUDENT_ID
    INNER JOIN DEPARTMENT d ON s.DEPT_ID=d.DEPT_ID;

-- 1:N 관계의 조인을하면 로우수가 늘어난다.
-- Inner join 은 조건에 만족하는(참조하는것이 null이 아닌) 데이터만 조인
SELECT *
    FROM DEPARTMENT  d
    INNER JOIN STUDENT s ON d.DEPT_ID=s.DEPT_ID;
-- OUTER JOIN : 조건에 만족하지 않는(참조하는것이 null인 경우도) 데이터도 조인
-- LEFT RIGHT FULL : 기준데이터를 어떤것으로 하겠냐?
-- INSERT INTO DEPARTMENT VALUES ('D04','시각디자인학과');
SELECT *
FROM DEPARTMENT d
    LEFT JOIN STUDENT s ON d.DEPT_ID=s.DEPT_ID;
SELECT * FROM STUDENT;

SELECT *
FROM DEPARTMENT d
    RIGHT JOIN STUDENT s ON d.DEPT_ID=s.DEPT_ID;
SELECT * FROM STUDENT;

SELECT *
FROM DEPARTMENT d
    FULL OUTER JOIN STUDENT s ON d.DEPT_ID=s.DEPT_ID;
-- SELECT * FROM STUDENT;

-- 서브쿼리 (쿼리 안에 쿼리가 존재 )
SELECT AVG(SCORE) FROM EXAM_SCORE;

SELECT * FROM EXAM_SCORE WHERE SCORE>82.11111111;

SELECT *
FROM EXAM_SCORE
WHERE SCORE>(SELECT AVG(SCORE) FROM EXAM_SCORE);

SELECT s.*,
       (SELECT DEPT_NAME FROM DEPARTMENT WHERE DEPT_ID=s.DEPT_ID) as 학부이름
FROM STUDENT s;

