--데어터 조작어 DML insert, update, delete, select(DQL)
SELECT * FROM EMP;
SELECT ENAME,JOB FROM EMP;
-- select 로 조회해서 만들어진 테이블을 가상테이블이라 한다. (물리적으로 존재하지 않기때문->VIEW)

SELECT * FROM EMP WHERE JOB='MANAGER';
SELECT * FROM EMP WHERE JOB='MANAGER' OR JOB='SALESMAN';
SELECT * FROM EMP WHERE JOB IN ('CLERK','SALESMAN');
SELECT * FROM EMP WHERE JOB IN ('CLERK','SALESMAN') ORDER BY JOB,HIREDATE DESC ;
SELECT * FROM EMP WHERE LOWER(JOB) IN ('clerk','salesman') ORDER BY JOB,HIREDATE DESC ;

SELECT ENAME,SAL FROM EMP WHERE SAL>=2000 AND SAL<=3000;
SELECT ENAME,SAL FROM EMP WHERE SAL BETWEEN 2000 AND 3000;

SELECT INITCAP(ENAME) as "사람 이름" FROM EMP;
SELECT INITCAP(ENAME) "사람 이름" FROM EMP;
-- SUBSTR,L,RPAD, LOW,UP,INITCAP
-- 테이블의 별칭 as 를 사용할수없다.
SELECT e.ENAME,e.SAL FROM EMP e;

SELECT ENAME,LPAD(JOB,10,'_') FROM EMP;

SELECT ENAME,ROUND(SAL,1) FROM EMP;

SELECT ENAME,TO_CHAR(HIREDATE,'MM"월"DD"일"') 입사일 FROM EMP;

SELECT ENAME,NVL(COMM,0) FROM EMP;
SELECT ENAME,COMM FROM EMP WHERE COMM=null;
SELECT ENAME,COMM FROM EMP WHERE COMM is null;
SELECT ENAME,COMM FROM EMP WHERE COMM is not null;
-- SELECT ENAME,COMM FROM EMP WHERE COMM is null OR COMM=0;
SELECT ENAME,COMM FROM EMP WHERE NVL(COMM,0)=0;
-- like %_ (문자열 검색)
SELECT EMPNO,ENAME FROM EMP WHERE ENAME ='k';
SELECT EMPNO,ENAME FROM EMP WHERE LOWER(ENAME) like '%k%';
SELECT EMPNO,ENAME FROM EMP WHERE LOWER(ENAME) like 'k%';
SELECT EMPNO,ENAME FROM EMP WHERE LOWER(ENAME) like '%k';
-- king, King, KING => king
SELECT EMPNO,ENAME FROM EMP WHERE ENAME like '%C___';
-- 집계된 하나의 결과를 반환하는 함수 집계함수 sum,avg,max,min,distinct
SELECT SUM(SAL),TRUNC(AVG(SAL),2),MAX(SAL),MIN(SAL) FROM EMP;
SELECT DISTINCT JOB FROM EMP;
-- SELECT DISTINCT JOB, SUM(SAL) FROM EMP;
-- distinct는 집계함수지만 다른집계와 같이 사용불가

SELECT JOB FROM EMP GROUP BY JOB;
SELECT JOB, SUM(SAL),COUNT(*) FROM EMP GROUP BY JOB;
SELECT JOB, AVG(NVL(COMM,0)),COUNT(NVL(COMM,0)),COUNT(*)  FROM EMP GROUP BY JOB;
-- 급여와 커미션의 합의 평균을 구하세요. 그룹을 부서별로 나누어 집계하세요.
SELECT * FROM EMP;
SELECT DEPTNO,TRUNC(AVG(SAL+NVL(COMM,0)),2) 급여와커미션의평균
FROM EMP
GROUP BY DEPTNO
HAVING TRUNC(AVG(SAL+NVL(COMM,0)),2)>=2000;
-- 별칭으로 HAVING 조회가 불가능
-- SELECT DEPTNO,TRUNC(AVG(SAL+NVL(COMM,0)),2) "급여와커미션의평균"
-- FROM EMP
-- GROUP BY DEPTNO
-- HAVING "급여와커미션의평균" >=2000;

-- SELECT ENAME 이름 FROM EMP WHERE 이름='KING';
-- from 절 서브쿼리 조회한 내역을 가상테이블로 사용
SELECT *
    FROM (SELECT ENAME 이름 FROM EMP) n
    WHERE n.이름='KING';

SELECT ENAME,DEPTNO FROM EMP;
-- 크로스조인 (모든 경우의 수를 만드는 조인)
SELECT ENAME,E.DEPTNO,
       D.DEPTNO,D.DNAME
FROM EMP E,DEPT D
ORDER BY ENAME;
-- 내부조인 (조건에 맞는 경우만 조회 조인)
SELECT e.ENAME,d.DEPTNO,d.DNAME
FROM EMP e,DEPT d
WHERE e.DEPTNO=d.DEPTNO
ORDER BY e.ENAME;

SELECT e.ENAME,d.*
FROM EMP e JOIN DEPT d
    ON e.DEPTNO=d.DEPTNO
ORDER BY d.DEPTNO;

SELECT e.ENAME,d.*
FROM EMP e FULL OUTER JOIN DEPT d
    ON e.DEPTNO=d.DEPTNO
ORDER BY d.DEPTNO;
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1111,'최경민','DEVELOPER',null,
        '2026-01-01',6000,null,null);
COMMIT;



