SELECT e.EMPNO,e.ENAME, e.MGR FROM EMP e;
SELECT e.EMPNO,e.ENAME, e.MGR, m.ENAME 상사이름
FROM EMP e LEFT JOIN EMP m ON e.MGR=m.EMPNO
ORDER BY e.EMPNO;
-- 참조키가 아닌 데이터간의 조인 (salgrade) : emp.sal 과 salgrade.hi,rowsal 은 참조관계가 아니다.
SELECT * FROM SALGRADE;
SELECT ENAME,SAL,s.*
FROM EMP e CROSS JOIN SALGRADE s
ORDER BY ENAME;
-- None-equi JOIN
SELECT ENAME,SAL,s.*
FROM EMP e JOIN SALGRADE s
ON e.SAL>=s.LOSAL AND e.SAL<=s.HISAL;

SELECT ENAME,SAL,s.*
FROM EMP e JOIN SALGRADE s
ON e.SAL>=s.LOSAL AND e.SAL<=s.HISAL
ORDER BY s.GRADE,e.SAL;


-- 급여와 커미션의 합으로 급여의 등급을 구하세요!
SELECT ENAME, SAL+NVL(COMM,0) "급여+커미션",s.GRADE
FROM EMP LEFT JOIN SALGRADE s
    ON SAL+NVL(COMM,0) BETWEEN LOSAL AND HISAL;






