SELECT * FROM EMP;
-- 부서번호는 모르는데 LOC=NEW YORK 지부에 배정된 사원은?
-- SELECT  * FROM DEPT;
SELECT ENAME,DEPTNO FROM EMP;
SELECT ENAME,DEPTNO
    FROM EMP
    WHERE DEPTNO=(
        SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK'
        );
-- 평균 급여보다 급여를 더 많이 받는 사원
SELECT ENAME,SAL FROM EMP
    WHERE SAL>(
        SELECT AVG(SAL) FROM EMP
        );
-- 서브쿼리를 조인으로 해결해기
-- SELECT * FROM EMP WHERE LOC='NEW YORK';
SELECT * FROM EMP NATURAL JOIN DEPT WHERE LOC='NEW YORK';

-- 단일행서브쿼리인데 필드에 존재하는 것
-- 스칼라서브쿼리 : 필드에 한개의 결과를 반환하는 서브쿼리
-- 상관서브쿼리 : 한 행의 결과를 서브쿼리에 사용
SELECT ENAME,DEPTNO FROM  EMP;
SELECT ENAME,DEPTNO,
       (SELECT DNAME FROM DEPT WHERE DEPTNO=EMP.DEPTNO) 부서이름
FROM  EMP;

-- 평균급여보다 더적게 급여를 받는 부서에 포함된 사원을 검색 ??

SELECT DEPTNO,TRUNC(AVG(SAL))  FROM EMP GROUP BY DEPTNO
HAVING AVG(SAL)<(SELECT AVG(SAL) FROM EMP);

SELECT * FROM EMP WHERE DEPTNO in(10,20);

SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO  FROM EMP GROUP BY DEPTNO
HAVING AVG(SAL)<(SELECT AVG(SAL) FROM EMP));


SELECT SAL+NVL(COMM,0)
FROM EMP
WHERE SAL+NVL(COMM,0) BETWEEN 2000 AND 3000
ORDER BY SAL+NVL(COMM,0);

SELECT  SAL+NVL(COMM,0) 실제급여 FROM EMP;
-- 별칭이 생성되는 시기가 where 이후기 때문에 where 에서 사용불가
-- (where,order,having,group 별칭사용불가)
-- SELECT  SAL+NVL(COMM,0) 실제급여 FROM EMP WHERE 실제급여 BETWEEN 2000 AND 3000;

SELECT * FROM (SELECT  SAL+NVL(COMM,0) 실제급여 FROM EMP)
WHERE 실제급여 BETWEEN 2000 AND 3000
ORDER BY 실제급여;

-- 출력행의 번호출 출력하는 함수 rownum(Orderby 보다 빨리 실행됨)
SELECT ROWNUM, ENAME,SAL FROM EMP;
SELECT ROWNUM, ENAME,SAL FROM EMP ORDER BY ENAME;
SELECT ROWNUM,e.* FROM (SELECT ENAME,SAL FROM EMP ORDER BY ENAME) e;



