--복수의 행을 반환하는 서브쿼리
--WHERE 에서 사용하는 멀티행 서브쿼리 in any all exists

SELECT * FROM EMP WHERE DEPTNO in (10,30);

SELECT DEPTNO,MAX(SAL) FROM EMP WHERE DEPTNO IS NOT NULL GROUP BY DEPTNO ;

SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO
FROM EMP
WHERE DEPTNO IS NOT NULL
GROUP BY DEPTNO
HAVING MAX(SAL)>=3000);
-- 각 부서별로 최대 급여를 받는 사원을 조회하세요 (서브쿼리로)
SELECT * FROM EMP WHERE SAL IN
(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

-- ANY(하나라도 만족) , ALL (모두를 만족하는) : 크기비교 (>,<)
SELECT * FROM EMP WHERE SAL > ANY (2000,1500,3000,4500);
-- 크다이면 최소값을 기준
SELECT * FROM EMP WHERE SAL < ANY (2000,1500,3000,4500);
-- 작다이면 최대값을 기존
-- 10번 부서의 사원 중 한명이라도 급여가 높은 사원
-- 10번 부서의 '어느(Ani) 급여'보다 큰 사원
SELECT SAL FROM EMP WHERE DEPTNO=10;
SELECT * FROM  EMP WHERE SAL > ANY(SELECT SAL FROM EMP WHERE DEPTNO=10);
SELECT * FROM  EMP WHERE SAL > (SELECT MIN(SAL) FROM EMP WHERE DEPTNO=10);

SELECT * FROM EMP WHERE SAL > ALL (2000,1500,3000,4500);
SELECT * FROM EMP WHERE SAL < ALL (2000,1500,3000,4500);
-- 10번 부서의 '모든(All) 급여'보다 큰 사원
SELECT * FROM EMP
WHERE SAL > ALL(SELECT SAL FROM EMP WHERE DEPTNO=10);

-- EXISTS  : 서브쿼리로만 사용가능 (서브쿼리 실행 내역이 한개라도 있으면 만족)
-- 조인을 한 자식 테이블이 있는지 조회할때 사용??

SELECT  * FROM  DEPT;
-- 참조하는 부서만 출력
-- SELECT DISTINCT d.* FROM  DEPT d INNER JOIN EMP e ON d.DEPTNO=e.DEPTNO;
SELECT * FROM DEPT WHERE DEPTNO IN(
SELECT DISTINCT DEPTNO FROM EMP);

SELECT * FROM DEPT d WHERE EXISTS(
    SELECT 1 FROM EMP e WHERE e.DEPTNO=d.DEPTNO
);
SELECT * FROM DEPT d WHERE NOT EXISTS(
    SELECT 1 FROM EMP e WHERE e.DEPTNO=d.DEPTNO
);


