SELECT * FROM PAY_HISTORY;
-- offset 을 이용한 페이징
--  1페이지page (5개씩 rows,size)
SELECT * FROM PAY_HISTORY OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;
-- offset 공식(Page-1)*rows
SELECT * FROM PAY_HISTORY OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;
SELECT * FROM PAY_HISTORY OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY;
-- mysql 페이징
-- SELECT * FROM PAY_HISTORY LIMIT 5 OFFSET 0 ;
-- SELECT * FROM PAY_HISTORY LIMIT 5 OFFSET 5 ;
-- SELECT * FROM PAY_HISTORY LIMIT 5 OFFSET 10 ;
SELECT * FROM PAY_HISTORY  OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;
SELECT * FROM PAY_HISTORY ORDER BY EMPNO OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;
-- 정렬을 하면 페이징이 바뀐다.

SELECT * FROM PAY_HISTORY ORDER BY AMOUNT DESC OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY;
SELECT * FROM PAY_HISTORY ORDER BY AMOUNT DESC FETCH FIRST 3 ROWS ONLY;
-- WITH TIES : 정렬의 필드의 동점인 것을 같이 가져온다.
SELECT * FROM PAY_HISTORY ORDER BY AMOUNT DESC FETCH FIRST 3 ROWS WITH TIES;

-- 전통적인 페이징 ROWNUM : 정렬된 행의 번호를 붙이고 페이징

SELECT * FROM PAY_HISTORY ORDER BY AMOUNT DESC;
-- ROWNUM 는 정렬 전에 번호를 만들기 때문에 꼭 서브쿼리로 작성
SELECT ROWNUM ,p.* FROM PAY_HISTORY p ORDER BY AMOUNT DESC;
SELECT ROWNUM,p.*
FROM (SELECT * FROM PAY_HISTORY ORDER BY AMOUNT DESC) p;
-- 전통적인 페이징 ROWNUM BEWEEN start AND end
-- start (page-1)*rows+1
-- end page*rows

SELECT ROWNUM,p.*
FROM (SELECT * FROM PAY_HISTORY ORDER BY AMOUNT DESC) p
WHERE ROWNUM BETWEEN 1 AND 5;
-- ROWNUM 으로 구간 자르기시 동작하지 않음
SELECT ROWNUM,p.*
FROM (SELECT * FROM PAY_HISTORY ORDER BY AMOUNT DESC) p
WHERE ROWNUM BETWEEN 6 AND 10;

SELECT * FROM (
    SELECT ROWNUM rn, p.*
    FROM (
        SELECT * FROM PAY_HISTORY ORDER BY AMOUNT DESC) p
        WHERE ROWNUM <= 10
) WHERE rn>=6;

