SELECT SUM(SAL) FROM EMP;
--분석함수 Over : 집계의 결과를 각행의 붙이는 것(조인과 유사)
SELECT e.*, SUM(SAL) OVER () 총급여 FROM EMP e;

SELECT * FROM EMP e,(SELECT  SUM(SAL) 총급여 FROM EMP);

-- PARTITION BY 그룹으로 집계한 결과를 각행에 맞게 배치???

SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY DEPTNO;

SELECT e.*, SUM(SAL) OVER(PARTITION BY DEPTNO) FROM EMP e;

-- 조인으로 분석함수를 대신할 수 있지만 분석함수가 더 직관적이다.
SELECT * FROM EMP e
    JOIN (SELECT DEPTNO,SUM(SAL) FROM EMP GROUP BY DEPTNO) d
    ON e.DEPTNO=d.DEPTNO;

-- 분석함수에서만 사용할 수 있는 함수
-- 분석함수는 일반적인 집계는 대부분 사용가능
-- ROW_NUMBER(),RANK(),DENSE_RANK(),NTILE()
SELECT ROWNUM,e.* FROM EMP e ORDER BY HIREDATE;
-- SELECT ROW_NUMBER() OVER ()NUM,e.* FROM EMP e ORDER BY HIREDATE;
--ORA-30485: 윈도우 지정(볼구간 지정)에 ORDER BY : ROW_NUMBER은 ORDER BY 를 꼭 사용
SELECT ROW_NUMBER() OVER (ORDER BY HIREDATE) NUM,e.* FROM EMP e;
SELECT ROW_NUMBER() OVER (ORDER BY SAL DESC ) NUM,e.* FROM EMP e;

SELECT * FROM (
    SELECT ROW_NUMBER() OVER ( ORDER BY SAL DESC ) rm, e.*
    FROM EMP e
) WHERE rm BETWEEN 11 AND 15;

SELECT SAL FROM EMP ORDER BY SAL;
SELECT  ROW_NUMBER() over (ORDER BY SAL) rm,SAL FROM EMP ORDER BY SAL;
SELECT  ROW_NUMBER() over (ORDER BY SAL) rm,SAL FROM EMP;
SELECT  RANK() over (ORDER BY SAL) rm,SAL FROM EMP;
SELECT  DENSE_RANK() over (ORDER BY SAL) rm,SAL FROM EMP;
-- 중복있어도 순위가 유지 (일반적인 랭크)

SELECT SUM(SAL) FROM EMP;

SELECT ENAME, SUM(SAL) OVER() 총합 FROM EMP;

SELECT ENAME,s.총합 FROM EMP,(SELECT SUM(SAL) 총합 FROM EMP) s;

SELECT ENAME,SUM(COMM) OVER() FROM EMP;
SELECT ENAME,SUM( SAL+NVL(COMM,0) ) OVER() FROM EMP;

SELECT NVL(TO_CHAR(DEPTNO), '부서없음' ), SUM(SAL) "총합" FROM EMP GROUP BY DEPTNO;

SELECT ENAME, DEPTNO,SAL, SUM(SAL) OVER(PARTITION BY DEPTNO) "부서별 총합" FROM EMP;
-- job 별로 총합과 평균을 분석함수로 집계결과를 출력하세요
SELECT ENAME, JOB, SAL FROM EMP ORDER BY JOB;
SELECT ENAME, JOB, SAL,
       SUM(SAL) OVER ( PARTITION BY JOB) "직책별총합",
       TRUNC(AVG(SAL) OVER ( PARTITION BY JOB), 2) "직책별평균"
FROM EMP ORDER BY JOB;
-- Order by 와 함께 사용가능한 윈도우 함수
SELECT ENAME,SAL,SUM(SAL) OVER (
    ORDER BY SAL
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) FROM EMP;


-- ROWNUM ROW_NUMBER

SELECT ROWNUM, ENAME FROM EMP;
SELECT ROWNUM, ENAME FROM EMP ORDER BY ENAME;
SELECT ROWNUM rm, e.* FROM (SELECT ENAME FROM EMP ORDER BY ENAME) e;

SELECT ROW_NUMBER() over (ORDER BY ENAME) rm, ENAME FROM EMP;


SELECT SAL, SUM(SAL) over (
    ORDER BY SAL
    ROWS BETWEEN 1 PRECEDING  AND 1 FOLLOWING
    ) FROM EMP;

SELECT DEPTNO, SAL,
    SUM(SAL) OVER(
        PARTITION BY DEPTNO
        ORDER BY SAL,EMPNO)
FROM EMP;
